version: 2
updates:
  # Unit 0 completed project
  - package-ecosystem: "nuget"
    directory: "/unit-0/completed"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "unit-0"

  # Unit 1 completed project
  - package-ecosystem: "nuget"
    directory: "/unit-1/completed"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "unit-1"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions" 