#!/bin/bash
# echo Running $BASH_SOURCE
# set | egrep GIT
# echo PWD is $PWD

# ensure on master before publishing
if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then
   # publish Unit 1 DoThis to Dropbox & site
   git archive -o ~/Dropbox/Petabridge/Public/Akka.NET\ Bootcamp\ Files/Unit-1.zip HEAD:src/Unit-1/DoThis/
   git archive -o ../petabridge.github.io/Unit-1.zip HEAD:src/Unit-1/DoThis/

   # publish Unit 2 DoThis to Dropbox & site
   git archive -o ~/Dropbox/Petabridge/Public/Akka.NET\ Bootcamp\ Files/Unit-2.zip HEAD:src/Unit-2/DoThis/
   git archive -o ../petabridge.github.io/Unit-2.zip HEAD:src/Unit-2/DoThis/

   # publish Unit 3 DoThis to Dropbox & site
   git archive -o ~/Dropbox/Petabridge/Public/Akka.NET\ Bootcamp\ Files/Unit-3.zip HEAD:src/Unit-3/DoThis/
   git archive -o ../petabridge.github.io/Unit-3.zip HEAD:src/Unit-3/DoThis/
fi